import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import { Header } from '@/components/Header'
import { SmoothScroll } from '@/components/SmoothScroll'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        rel: 'icon',
        type: 'image/ico',
        url: 'images/favicon/favicon.ico',
      },
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '16x16',
        url: 'images/favicon/favicon-16x16.png',
      },
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '32x32',
        url: 'images/favicon/favicon-32x32.png',
      },
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '192x192',
        url: 'images/favicon/android-chrome-192x192.png',
      },
      {
        rel: 'icon',
        type: 'image/png',
        sizes: '512x512',
        url: 'images/favicon/android-chrome-512x512.png',
      },
    ],
  },
  manifest: 'images/favicon/site.webmanifest',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header />

        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  )
}
